#ifndef AIROBOT_BOARD_PINS_H
#define AIROBOT_BOARD_PINS_H

#include "stm32f1xx_hal.h"

#define ENCODER_A_PORT GPIOA
#define ENCODER_A_PIN GPIO_PIN_0
#define ENCODER_B_PORT GPIOA
#define ENCODER_B_PIN GPIO_PIN_1
#define ENCODER_SW_PORT GPIOA
#define ENCODER_SW_PIN GPIO_PIN_2

#define ESP_NSS_PORT GPIOA
#define ESP_NSS_PIN GPIO_PIN_4
#define ESP_SCK_PORT GPIOA
#define ESP_SCK_PIN GPIO_PIN_5
#define ESP_MISO_PORT GPIOA
#define ESP_MISO_PIN GPIO_PIN_6
#define ESP_MOSI_PORT GPIOA
#define ESP_MOSI_PIN GPIO_PIN_7

#define MOTOR_LEFT_PORT GPIOA
#define MOTOR_LEFT_IN1 GPIO_PIN_8
#define MOTOR_LEFT_IN2 GPIO_PIN_9
#define MOTOR_LEFT_IN3 GPIO_PIN_10
#define MOTOR_LEFT_IN4 GPIO_PIN_11
#define MOTOR_LEFT_PINS (MOTOR_LEFT_IN1 | MOTOR_LEFT_IN2 | MOTOR_LEFT_IN3 | MOTOR_LEFT_IN4)

#define MOTOR_RIGHT_PORT GPIOB
#define MOTOR_RIGHT_IN1 GPIO_PIN_0
#define MOTOR_RIGHT_IN2 GPIO_PIN_1
#define MOTOR_RIGHT_IN3 GPIO_PIN_10
#define MOTOR_RIGHT_IN4 GPIO_PIN_11
#define MOTOR_RIGHT_PINS (MOTOR_RIGHT_IN1 | MOTOR_RIGHT_IN2 | MOTOR_RIGHT_IN3 | MOTOR_RIGHT_IN4)

#define OLED_SDA_PORT GPIOB
#define OLED_SDA_PIN GPIO_PIN_6
#define OLED_SCL_PORT GPIOB
#define OLED_SCL_PIN GPIO_PIN_7

#define W25Q_CS_PORT GPIOB
#define W25Q_CS_PIN GPIO_PIN_12
#define W25Q_SCK_PORT GPIOB
#define W25Q_SCK_PIN GPIO_PIN_13
#define W25Q_MISO_PORT GPIOB
#define W25Q_MISO_PIN GPIO_PIN_14
#define W25Q_MOSI_PORT GPIOB
#define W25Q_MOSI_PIN GPIO_PIN_15

#define STATUS_LED_PORT GPIOC
#define STATUS_LED_PIN GPIO_PIN_13

#endif
